repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
    - id: isort
- repo: https://github.com/ambv/black
  rev: 22.6.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
- repo: local
  hooks:
    - id: unittests
      name: project unit tests
      entry: python -m unittest
      language: system
      pass_filenames: false
      args: ["discover"]
